#
# Deploys the app to a Dokku instance when merging into main.
#
# Requirements:
#
#   - secrets.DOKKU_SSH_URL - e.g. "ssh://dokku@example.com:2222/hamsat"
#   - secrets.DOKKU_PRIVATE_KEY - SSH private key
#
on:
  push:
    branches:
      - main

name: Deploy to Dokku

jobs:
  push_to_dokku:
    name: Push to Dokku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ secrets.DOKKU_SSH_URL }}
          ssh_private_key: ${{ secrets.DOKKU_PRIVATE_KEY }}
          git_push_flags: --force
